---

sudo: true

language: python

python:
  - 2.7

services:
  - docker

install:
  - pip install --upgrade pip
  - pip install pylint
  - pip install -r requirements.txt

script:
  - pylint docker_test_runner.py
  - ./docker_test_runner.py -f docker_test_runner.yml -t 3
