---

- debug:
    msg: "injected_dict: Key: {{ item.key }}, Value: {{ item.value }}"
  loop: "{{ injected_dict | dict2items }}"

- debug:
    msg: "injected_list: Item: {{ item }}"
  loop: "{{ injected_list | flatten(levels=1) }}"

- debug:
    msg: "injected_variable: {{ injected_variable }}"

- debug:
    msg: "override_variable: {{ override_variable }}"
